FROM python:3.10-slim

WORKDIR /code
	
COPY ./requirements.txt /code/requirements.txt
RUN apt-get update && apt-get install -y build-essential g++ 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt 
RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH
WORKDIR $HOME/app
COPY --chown=user . $HOME/app




CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
